export type Service = {
  id: string;
  slug: string;
  name: string;
  description: string;
  fullDescription?: string | null;
  category: string;
  imageUrl: string;
  galleryImages?: string[];
  priceFrom: number | null;
  priceTo?: number | null;
  priceLabel?: string | null;
  durationMinutes: number;
  durationLabel?: string | null;
  requiresQuote: boolean;
  featured?: boolean;
  active?: boolean;
  bookingEnabled?: boolean;
  whatsappEnabled?: boolean;
  showStaffSelector?: boolean;
  allowAnyStaff?: boolean;
  requiresDeposit?: boolean;
  depositAmount?: number | null;
  showOnHome?: boolean;
  sortOrder?: number;
  internalNotes?: string | null;
  beforeCare?: string | null;
  afterCare?: string | null;
  whatsappMessage?: string | null;
  prepMinutes?: number | null;
  bufferAfterMinutes?: number | null;
  source?: "base" | "custom";
  recommendations: string[];
  includes: string[];
  excludes: string[];
};
